name: E-Commerce CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build and run tests
        run: |
          cd backend
          mvn -B clean verify

      - name: Log in to Docker Hub
        run: echo "${{ secrets.dckr_pat_YbEyEW013VzLeNIv7eNMwTNPsqw }}" | docker login -u "${{ secrets.tanujamarni }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.tanujamarni }}/ecommerce:${{ github.sha }} .
          docker tag ${{ secrets.tanujamarni }}/ecommerce:${{ github.sha }} ${{ secrets.tanujamarni }}/ecommerce:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.tanujamarni }}/ecommerce:${{ github.sha }}
          docker push ${{ secrets.tanujamarni }}/ecommerce:latest
