name: E-Commerce CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣ Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Build and run Maven tests
      - name: Build and run tests
        run: |
          cd backend
          mvn -B clean verify

      # 4️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.tanujamarni}}
          password: ${{ secrets.dckr_pat_YbEyEW013VzLeNIv7eNMwTNPsqw}}
          registry: docker.io

      # 5️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.tanujamarni}}/ecommerce:${{ github.sha }} .
          docker tag ${{ secrets.tanujamarni}}/ecommerce:${{ github.sha }} ${{ secrets.tanujamarni}}/ecommerce:latest

      # 6️⃣ Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.tanujamarni}}/ecommerce:${{ github.sha }}
          docker push ${{ secrets.tan ujamarni}}/ecommerce:latest
